{{- if and .Values.secrets.create .Values.secrets.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStoreName | default "akeyless" }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: {{ .Values.secrets.external.secretPath }}
        property: database-url
    - secretKey: access-secret
      remoteRef:
        key: {{ .Values.secrets.external.secretPath }}
        property: access-secret
    - secretKey: refresh-secret
      remoteRef:
        key: {{ .Values.secrets.external.secretPath }}
        property: refresh-secret
    - secretKey: vapid-public-key
      remoteRef:
        key: {{ .Values.secrets.external.secretPath }}
        property: vapid-public-key
    - secretKey: vapid-private-key
      remoteRef:
        key: {{ .Values.secrets.external.secretPath }}
        property: vapid-private-key
{{- end }}
