namespaceOverride: ""

backend:
  replicaCount: 1
  image:
    repository: ghcr.io/qper/hflow/backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8080
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env: {}

frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/qper/hflow/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

migrations:
  image:
    repository: ghcr.io/qper/hflow/backend
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

serviceMonitor:
  enabled: false
  namespace: ""

ingress:
  enabled: false
  className: traefik
  host: habitflow.local
  annotations: {}

secrets:
  create: true
  name: habitflow-secrets
  external:
    enabled: false
    kind: ExternalSecret
    provider: akeyless
    secretPath: "habitflow/default"

imagePullSecrets: []
